/*
 * Julianne Wojdak
 * 05/11/18
 * Predefined Methods
 */

/**
 *
 * @author JuWoj8013
 */
public class FormPredefinedMethods extends javax.swing.JFrame {

    /**
     * Creates new form FormPredefinedMethods
     */
    public FormPredefinedMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        LargestLabel1 = new javax.swing.JLabel();
        LargestText1 = new javax.swing.JTextField();
        LargestText2 = new javax.swing.JTextField();
        LargestButton = new javax.swing.JButton();
        SmallestLabel1 = new javax.swing.JLabel();
        LargestLabel2 = new javax.swing.JLabel();
        SmallestText1 = new javax.swing.JTextField();
        SmallestText2 = new javax.swing.JTextField();
        SmallestButton = new javax.swing.JButton();
        SmallestLabel2 = new javax.swing.JLabel();
        PowerLabel1 = new javax.swing.JLabel();
        PowerText1 = new javax.swing.JTextField();
        PowerText2 = new javax.swing.JTextField();
        PowerButton = new javax.swing.JButton();
        PowerLabel2 = new javax.swing.JLabel();
        HypotLabel1 = new javax.swing.JLabel();
        HypotText1 = new javax.swing.JTextField();
        HypotText2 = new javax.swing.JTextField();
        HypotButton = new javax.swing.JButton();
        HypotLabel2 = new javax.swing.JLabel();
        RoundDLabel1 = new javax.swing.JLabel();
        RoundDText = new javax.swing.JTextField();
        RoundDButton = new javax.swing.JButton();
        RoundDLabel2 = new javax.swing.JLabel();
        RoundULabel1 = new javax.swing.JLabel();
        RoundUText = new javax.swing.JTextField();
        RoundUButton = new javax.swing.JButton();
        RoundULabel2 = new javax.swing.JLabel();
        RootLabel1 = new javax.swing.JLabel();
        RootText = new javax.swing.JTextField();
        RootButton = new javax.swing.JButton();
        RootLabel2 = new javax.swing.JLabel();
        RadiansLabel1 = new javax.swing.JLabel();
        RadiansText = new javax.swing.JTextField();
        RadiansButton = new javax.swing.JButton();
        RadiansLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        HeadingLabel.setFont(new java.awt.Font("ZurichGreek BT", 0, 18)); // NOI18N
        HeadingLabel.setText("Magical Math Methods");

        LargestLabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        LargestLabel1.setText("Enter two numbers and click the button to display the largest.");

        LargestText1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        LargestText2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        LargestButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        LargestButton.setText("Largest");
        LargestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargestButtonActionPerformed(evt);
            }
        });

        SmallestLabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        SmallestLabel1.setText("Enter two number abd click the button to display the smallest.");

        LargestLabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        SmallestText1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        SmallestText2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        SmallestButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        SmallestButton.setText("Smallest");
        SmallestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallestButtonActionPerformed(evt);
            }
        });

        SmallestLabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        PowerLabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        PowerLabel1.setText("Enter two numbers and click the button to display the first number to the power of the second.");

        PowerText1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        PowerText2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        PowerButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        PowerButton.setText("To The Power Of");
        PowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButtonActionPerformed(evt);
            }
        });

        PowerLabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        HypotLabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        HypotLabel1.setText("Enter the lengths of to sides of a triangle and click the button to display the hypotenuse.");

        HypotText1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        HypotText2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        HypotButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        HypotButton.setText("Hypotenuse");
        HypotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HypotButtonActionPerformed(evt);
            }
        });

        HypotLabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RoundDLabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RoundDLabel1.setText("Enter a decimal value and click the button to display the value rounded down to the nearest integer.");

        RoundDText.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RoundDButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RoundDButton.setText("Rounded Down");
        RoundDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundDButtonActionPerformed(evt);
            }
        });

        RoundDLabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RoundULabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RoundULabel1.setText("Enter a decimal value and click the button to display the value rounded up to the nearest integer.");

        RoundUText.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RoundUButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RoundUButton.setText("Rounded Up");
        RoundUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundUButtonActionPerformed(evt);
            }
        });

        RoundULabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RootLabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RootLabel1.setText("Enter an integer and click the button to display the square root of the integer");

        RootText.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RootButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RootButton.setText("Square Root");
        RootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RootButtonActionPerformed(evt);
            }
        });

        RootLabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RadiansLabel1.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RadiansLabel1.setText("Enter an angle in degrees and click the button to display the angle in radius.");

        RadiansText.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        RadiansButton.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N
        RadiansButton.setText("In Radians");
        RadiansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiansButtonActionPerformed(evt);
            }
        });

        RadiansLabel2.setFont(new java.awt.Font("ZurichGreek BT", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LargestLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SmallestLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(HypotLabel1)
                    .addComponent(RoundDLabel1)
                    .addComponent(PowerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadiansLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoundULabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(SmallestText1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SmallestText2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(SmallestButton)
                                            .addGap(54, 54, 54)
                                            .addComponent(SmallestLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(LargestText1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LargestText2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(LargestButton)
                                            .addGap(63, 63, 63)
                                            .addComponent(LargestLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(HeadingLabel))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(PowerText1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PowerText2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(PowerButton)
                                    .addGap(44, 44, 44)
                                    .addComponent(PowerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(HypotText1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HypotText2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(HypotButton)
                                    .addGap(55, 55, 55)
                                    .addComponent(HypotLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(RoundDText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(RoundDButton)
                                    .addGap(43, 43, 43)
                                    .addComponent(RoundDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(RootLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(RoundUText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61)
                                    .addComponent(RoundUButton)
                                    .addGap(59, 59, 59)
                                    .addComponent(RoundULabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(RootText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(RootButton)
                                    .addGap(60, 60, 60)
                                    .addComponent(RootLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(RadiansText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(RadiansButton)
                                .addGap(70, 70, 70)
                                .addComponent(RadiansLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LargestLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LargestLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LargestText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LargestText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LargestButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SmallestLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SmallestLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SmallestButton)
                        .addComponent(SmallestText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SmallestText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PowerLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PowerButton)
                    .addComponent(PowerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PowerText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HypotLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(HypotLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HypotButton)
                            .addComponent(HypotText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HypotText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoundDLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoundDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoundDButton)
                    .addComponent(RoundDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoundULabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoundUButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RoundUText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RoundULabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RootLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RootText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RootButton)
                    .addComponent(RootLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadiansLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadiansText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RadiansButton))
                    .addComponent(RadiansLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LargestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargestButtonActionPerformed
        int num1 = Integer.parseInt(LargestText1.getText());
        int num2 = Integer.parseInt(LargestText2.getText());
  
        LargestLabel2.setText("The largest number is " + (Math.max(num1, num2)));
    }//GEN-LAST:event_LargestButtonActionPerformed

    private void SmallestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallestButtonActionPerformed
        int num1 = Integer.parseInt(SmallestText1.getText());
        int num2 = Integer.parseInt(SmallestText2.getText());
        
        SmallestLabel2.setText("The smallest number is " + (Math.min(num1, num2)));
    }//GEN-LAST:event_SmallestButtonActionPerformed

    private void PowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButtonActionPerformed
        int num1 = Integer.parseInt(PowerText1.getText());
        int num2 = Integer.parseInt(PowerText2.getText());
        
        PowerLabel2.setText("The answer is " + (Math.pow(num1, num2)));
    }//GEN-LAST:event_PowerButtonActionPerformed

    private void HypotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HypotButtonActionPerformed
        int num1 = Integer.parseInt(HypotText1.getText());
        int num2 = Integer.parseInt(HypotText2.getText());
        
        HypotLabel2.setText("The hypotenuse is " + (Math.hypot(num1, num2)));
    }//GEN-LAST:event_HypotButtonActionPerformed

    private void RoundDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundDButtonActionPerformed
        double num1 = Double.parseDouble(RoundDText.getText());
        
        RoundDLabel2.setText("The number rounded down is "+ (Math.floor(num1)));
    }//GEN-LAST:event_RoundDButtonActionPerformed

    private void RoundUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundUButtonActionPerformed
        double num1 = Double.parseDouble(RoundUText.getText());
        
        RoundULabel2.setText("The number rounded up is " + (Math.ceil(num1)));
    }//GEN-LAST:event_RoundUButtonActionPerformed

    private void RootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RootButtonActionPerformed
        int num1 = Integer.parseInt(RootText.getText());
        
        RootLabel2.setText("The square root of the number is " + (Math.sqrt(num1)));
    }//GEN-LAST:event_RootButtonActionPerformed

    private void RadiansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiansButtonActionPerformed
        int num1 = Integer.parseInt(RadiansText.getText());
        
        RadiansLabel2.setText("The angle in radius is " + (Math.toRadians(num1)));
    }//GEN-LAST:event_RadiansButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPredefinedMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPredefinedMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPredefinedMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPredefinedMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPredefinedMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JButton HypotButton;
    private javax.swing.JLabel HypotLabel1;
    private javax.swing.JLabel HypotLabel2;
    private javax.swing.JTextField HypotText1;
    private javax.swing.JTextField HypotText2;
    private javax.swing.JButton LargestButton;
    private javax.swing.JLabel LargestLabel1;
    private javax.swing.JLabel LargestLabel2;
    private javax.swing.JTextField LargestText1;
    private javax.swing.JTextField LargestText2;
    private javax.swing.JButton PowerButton;
    private javax.swing.JLabel PowerLabel1;
    private javax.swing.JLabel PowerLabel2;
    private javax.swing.JTextField PowerText1;
    private javax.swing.JTextField PowerText2;
    private javax.swing.JButton RadiansButton;
    private javax.swing.JLabel RadiansLabel1;
    private javax.swing.JLabel RadiansLabel2;
    private javax.swing.JTextField RadiansText;
    private javax.swing.JButton RootButton;
    private javax.swing.JLabel RootLabel1;
    private javax.swing.JLabel RootLabel2;
    private javax.swing.JTextField RootText;
    private javax.swing.JButton RoundDButton;
    private javax.swing.JLabel RoundDLabel1;
    private javax.swing.JLabel RoundDLabel2;
    private javax.swing.JTextField RoundDText;
    private javax.swing.JButton RoundUButton;
    private javax.swing.JLabel RoundULabel1;
    private javax.swing.JLabel RoundULabel2;
    private javax.swing.JTextField RoundUText;
    private javax.swing.JButton SmallestButton;
    private javax.swing.JLabel SmallestLabel1;
    private javax.swing.JLabel SmallestLabel2;
    private javax.swing.JTextField SmallestText1;
    private javax.swing.JTextField SmallestText2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
